Update kernel.yml

diff --git a/.github/workflows/kernel.yml b/.github/workflows/kernel.yml
--- a/.github/workflows/kernel.yml
+++ b/.github/workflows/kernel.yml
@@ -13,7 +13,7 @@ jobs:
       uses: actions/checkout@main
       with:
         repository: kdrag0n/proton-clang
-        path: clang
+        path: clang-llvm
 
     - name: Checkout AnyKernel3
       uses: actions/checkout@main
@@ -24,66 +24,228 @@ jobs:
     - name: Checkout kernel
       uses: actions/checkout@main
       with:
-        repository: SuperiorOS-Devices/kernel_motorola_payton
-        path: kernel
+        repository: theoware/cybertron
 
     - name: Setup env
-      run: sudo apt-get install device-tree-compiler bc cpio ccache zip gcc make gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
+      run: sudo apt-get install device-tree-compiler bc cpio zip gcc make
+
+    - uses: actions/setup-java@main
+      with:
+        distribution: 'temurin'
+        java-version: '17'
 
     - name: Run a script
       run: |
-        mkdir -p out
-        export ZIPNAME=cybertron.zip
-        export ARCH=arm64
-        export SUBARCH=arm64
-        export CLANG_PATH=${{ github.workspace}}/clang/bin
-        export PATH=/usr/lib/ccache:${PATH}
-        export PATH=${CLANG_PATH}:${PATH}
-        export CLANG_TRIPLE=aarch64-linux-gnu-
-        export CROSS_COMPILE=$CLANG_PATH/aarch64-linux-gnu-
-        export CROSS_COMPILE_ARM32=$CLANG_PATH/arm-linux-gnueabi-
+        # Bail out if script fails
+        set -e
 
-        ls -R /home/runner/work/test/test/clang/bin/
+        # Function to show an informational message
+        msg() {
+          echo
+          echo -e "\e[1;32m$*\e[0m"
+          echo
+        }
 
-        cd kernel
-        echo $PWD
+        err() {
+          echo -e "\e[1;41m$*\e[0m"
+          exit 1
+        }
 
-        echo
-        echo "Clean Build Directory"
-        echo 
+        cdir() {
+          cd "$1" 2>/dev/null || \
+            err "The directory $1 doesn't exists !"
+        }
 
-        make clean && make mrproper
+        ##------------------------------------------------------##
+        ##----------Basic Informations, COMPULSORY--------------##
 
-        echo
-        echo "Issue Build Commands"
-        echo
+        # The defult directory where the kernel should be placed
+        KERNEL_DIR="$(pwd)"
+        BASEDIR="$(basename "$KERNEL_DIR")"
 
-        mkdir -p out
+        ZIPNAME="cybertron"
+        AUTHOR="cool585"
+        ARCH=arm64
+        MODEL="Motorola X4"
+        DEVICE="payton"
+        DEFCONFIG=cybertron_payton_defconfig
+        LINKER=ld.lld
+        FILES=Image.gz-dtb
+        SIGN=1
+        SILENCE=0
+        VERBOSE=0
+        LOG_DEBUG=0
 
-        echo
-        echo "Set DEFCONFIG"
-        echo 
-        make cybertron_payton_defconfig CC=clang O=out 
+        # Check if we are using a dedicated CI ( Continuous Integration ), and
+        # set KBUILD_BUILD_VERSION and KBUILD_BUILD_HOST and CI_BRANCH
 
-        echo
-        echo "Build The Good Stuff"
-        echo 
+        ## Set defaults first
 
-        make -j$(nproc) O=out CC="ccache clang" AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip
+        # shellcheck source=/etc/os-release
+        DISTRO=$(source /etc/os-release && echo "${NAME}")
+        KBUILD_BUILD_HOST=$(uname -a | awk '{print $2}')
+        CI_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+        TERM=xterm
+        export KBUILD_BUILD_HOST CI_BRANCH TERM
 
-        cd ..
+        ## Check for CI
+        if [ "$CI" ]
+        then
+          if [ "$CIRCLECI" ]
+          then
+            export KBUILD_BUILD_VERSION=$CIRCLE_BUILD_NUM
+            export KBUILD_BUILD_HOST="CircleCI"
+            export CI_BRANCH=$CIRCLE_BRANCH
+          fi
+          if [ "$DRONE" ]
+          then
+            export KBUILD_BUILD_VERSION=$DRONE_BUILD_NUMBER
+            export KBUILD_BUILD_HOST=$DRONE_SYSTEM_HOST
+            export CI_BRANCH=$DRONE_BRANCH
+            export BASEDIR=$DRONE_REPO_NAME # overriding
+            export SERVER_URL="${DRONE_SYSTEM_PROTO}://${DRONE_SYSTEM_HOSTNAME}/${AUTHOR}/${BASEDIR}/${KBUILD_BUILD_VERSION}"
+          else
+            echo "Not presetting Build Version"
+          fi
+        fi
 
-        ls kernel/out/arch/arm64/boot/
+        #Check Kernel Version
+        KERVER=$(make kernelversion)
 
-        cp kernel/out/arch/arm64/boot/Image.gz-dtb ./AnyKernel3
 
-        cp anykernel.patch ./AnyKernel3
+        # Set a commit head
+        COMMIT_HEAD=$(git log --oneline -1)
 
-        cd AnyKernel3
+        # Set Date 
+        DATE=$(TZ=Europe/Berlin date +"%Y%m%d-%T")
 
-        zip "../$ZIPNAME" * -x '*.git*' README.md *placeholder
+        #Now Its time for other stuffs like cloning, exporting, etc
+
+         clone() {
+          echo " "
+
+          if [ $COMPILER = "clang" ]
+          then
+            TC_DIR=$KERNEL_DIR/clang-llvm
+          fi
+
+          msg "|| Cloning arm-linux-androideabi-4.9 and aarch64-linux-android-4.9 ||"
+          git clone --depth 1 --no-single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9.git
+          git clone --depth 1 --no-single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git
+          cd arm-linux-androideabi-4.9
+          git reset --hard 4d16d93f49c2b5ecdd0f12c38d194835dd595603
+          cd ..
+          cd aarch64-linux-android-4.9
+          git reset --hard 0a0604336d4d1067aa1aaef8d3779b31fcee841d
+          cd ..
+
+        ##------------------------------------------------------##
+
+        exports() {
+          KBUILD_BUILD_USER=$AUTHOR
+          SUBARCH=$ARCH
+
+          if [ $COMPILER = "clang" ]
+          then
+            KBUILD_COMPILER_STRING=$("$TC_DIR"/bin/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')
+            PATH=$TC_DIR/bin/:$TC_DIR/aarch64-linux-gnu/bin/:$PATH
+          elif [ $COMPILER = "gcc" ]
+          then
+            KBUILD_COMPILER_STRING=$("$GCC64_DIR"/bin/aarch64-elf-gcc --version | head -n 1)
+            PATH=$GCC64_DIR/bin/:$GCC32_DIR/bin/:/usr/bin:$PATH
+          fi
+
+          PROCS=$(nproc --all)
+
+            PATH="${KERNEL_DIR}/clang-llvm/bin:${KERNEL_DIR}/aarch64-linux-android-4.9/bin:${KERNEL_DIR}/arm-linux-androideabi-4.9/bin:${PATH}"
+
+          export KBUILD_BUILD_USER ARCH SUBARCH PATH \
+            KBUILD_COMPILER_STRING BOT_MSG_URL \
+            BOT_BUILD_URL PROCS
+        }
+
+        build_kernel() {
+          if [ $INCREMENTAL = 0 ]
+          then
+            msg "|| Cleaning Sources ||"
+            make clean && make mrproper && rm -rf out
+          fi
+
+          make O=out $DEFCONFIG
+
+          BUILD_START=$(date +"%s")
+
+          MAKE+=(
+            CROSS_COMPILE=aarch64-linux-gnu- \
+            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
+            CC=clang \
+            AR=llvm-ar \
+            OBJDUMP=llvm-objdump \
+            STRIP=llvm-strip \
+            LD="$LINKER"
+          )
+
+          if [ $SILENCE = "1" ]
+          then
+            MAKE+=( -s )
+          fi
+
+          msg "|| Started Compilation ||"
+          make -kj"$PROCS" O=out \
+            NM=llvm-nm \
+            OBJCOPY=llvm-objcopy \
+            V=$VERBOSE \
+            "${MAKE[@]}" 2>&1 | tee error.log
+          if [ $MODULES = "1" ]
+          then
+              msg "|| Started Compiling Modules ||"
+              make -j"$PROCS" O=out \
+             "${MAKE[@]}" modules_prepare
+              make -j"$PROCS" O=out \
+             "${MAKE[@]}" modules INSTALL_MOD_PATH="$KERNEL_DIR"/out/modules
+              make -j"$PROCS" O=out \
+             "${MAKE[@]}" modules_install INSTALL_MOD_PATH="$KERNEL_DIR"/out/modules
+              find "$KERNEL_DIR"/out/modules -type f -iname '*.ko' -exec cp {} AnyKernel3/modules/system/lib/modules/ \;
+          fi
+
+            BUILD_END=$(date +"%s")
+            DIFF=$((BUILD_END - BUILD_START))
+
+            if [ -f "$KERNEL_DIR"/out/arch/arm64/boot/$FILES ]
+            then
+              msg "|| Kernel successfully compiled ||"
+                gen_zip
+              else
+            fi
+
+        }
+
+        ##--------------------------------------------------------------##
+
+        gen_zip() {
+          msg "|| Zipping into a flashable zip ||"
+          mv "$KERNEL_DIR"/out/arch/arm64/boot/$FILES AnyKernel3/$FILES
+          cdir AnyKernel3
+          zip -r $ZIPNAME-$DEVICE-"$DATE" . -x ".git*" -x "README.md" -x "*.zip"
+
+          ## Prepare a final zip variable
+          ZIP_FINAL="$ZIPNAME-$DEVICE-$DATE"
+
+          if [ $SIGN = 1 ]
+          then
+            curl -sLo zipsigner-3.0.jar https://github.com/Magisk-Modules-Repo/zipsigner/raw/master/bin/zipsigner-3.0-dexed.jar
+            java -jar zipsigner-3.0.jar "$ZIP_FINAL".zip "$ZIP_FINAL"-signed.zip
+            ZIP_FINAL="$ZIP_FINAL-signed"
+          fi
+          cd ..
+        }
+
+        clone
+        exports
+        build_kernel
+
     - uses: actions/upload-artifact@main
       with:
         name: kernel
         path: | 
-          ./kernel/out/arch/arm64/boot/
+          ./kernel/out/arch/arm64/
